/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ouc.minica.view;
 
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.security.InvalidKeyException;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.NoSuchAlgorithmException;
import java.security.NoSuchProviderException;
import java.security.SecureRandom;
import java.security.Security;
import java.security.SignatureException;
import java.security.cert.CertificateEncodingException;
import java.security.cert.X509Certificate;
import java.text.SimpleDateFormat; 
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import org.bouncycastle.asn1.x509.X509Name;
import org.bouncycastle.jce.X509V3CertificateGenerator;
import org.bouncycastle.jce.provider.BouncyCastleProvider;
/**
 *
 * @author Administrator
 */
public class GenerateFrame extends javax.swing.JFrame {
    /**
     * Creates new form generateframe
     */
    public GenerateFrame() {
        initComponents();
    }
    private static final String[] info={"","","","","","","","","","","","","",""};//存放字段信息
    private static String subjectDN="";
    Date now = new Date(); 
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyyMMddHHmmss");//可以方便地修改日期格式
    private final String serialnum = dateFormat.format( now ); //证书序列号
    private int length; 
    private String path;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jInternalFrame = new javax.swing.JInternalFrame();
        jPCert = new javax.swing.JPanel();
        jPCertStorage = new javax.swing.JPanel();
        PathShow = new javax.swing.JLabel();
        btnFileChoose = new javax.swing.JButton();
        jLabelFile = new javax.swing.JLabel();
        btnMake = new javax.swing.JButton();
        jPConstraint = new javax.swing.JPanel();
        jPCertForm = new javax.swing.JPanel();
        jLabelDER = new javax.swing.JLabel();
        jPCertFunction = new javax.swing.JPanel();
        jLabelKeyLength = new javax.swing.JLabel();
        jLabelEffDate = new javax.swing.JLabel();
        jTextDAY = new javax.swing.JTextField();
        jLabelDay = new javax.swing.JLabel();
        jLabelLEN = new javax.swing.JLabel();
        keyLength = new javax.swing.JComboBox();
        jPCertStyle = new javax.swing.JPanel();
        jRBROOT = new javax.swing.JRadioButton();
        jRBnDIY = new javax.swing.JRadioButton();
        jLabelNavImage = new javax.swing.JLabel();
        jPInfo = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelContent = new javax.swing.JLabel();
        jCBCountry = new javax.swing.JCheckBox();
        jCBProvince = new javax.swing.JCheckBox();
        jCBCity = new javax.swing.JCheckBox();
        jCBCommunity = new javax.swing.JCheckBox();
        jCBUnit = new javax.swing.JCheckBox();
        jCBMail = new javax.swing.JCheckBox();
        jCBSurName = new javax.swing.JCheckBox();
        jCBTeleNum = new javax.swing.JCheckBox();
        jCBStreet = new javax.swing.JCheckBox();
        jCBPoBox = new javax.swing.JCheckBox();
        jCBPoCode = new javax.swing.JCheckBox();
        jCBID = new javax.swing.JCheckBox();
        jCBName = new javax.swing.JCheckBox();
        jLabelImage1 = new javax.swing.JLabel();
        jLabelImage2 = new javax.swing.JLabel();
        jLabelImage3 = new javax.swing.JLabel();
        jLabelImage4 = new javax.swing.JLabel();
        jLabelImage5 = new javax.swing.JLabel();
        jLabelImage6 = new javax.swing.JLabel();
        jLabelImage7 = new javax.swing.JLabel();
        jLabelImage8 = new javax.swing.JLabel();
        jLabelImage9 = new javax.swing.JLabel();
        jLabelImage10 = new javax.swing.JLabel();
        jLabelImage11 = new javax.swing.JLabel();
        jLabelImage12 = new javax.swing.JLabel();
        jLabelImage13 = new javax.swing.JLabel();
        jCBPhoneNum = new javax.swing.JCheckBox();
        jLabelImage14 = new javax.swing.JLabel();
        jLabelTextName = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTFname = new javax.swing.JTextField();
        jTFcountry = new javax.swing.JTextField();
        jTFprovince = new javax.swing.JTextField();
        jTFcity = new javax.swing.JTextField();
        jTFcommunity = new javax.swing.JTextField();
        jTFunit = new javax.swing.JTextField();
        jTFemail = new javax.swing.JTextField();
        jTFsurname = new javax.swing.JTextField();
        jTFtelephone = new javax.swing.JTextField();
        jTFstreet = new javax.swing.JTextField();
        jTFpobox = new javax.swing.JTextField();
        jTFpocode = new javax.swing.JTextField();
        jTFID = new javax.swing.JTextField();
        jTFphone = new javax.swing.JTextField();
        jTFName = new javax.swing.JTextField();
        jTFCountry = new javax.swing.JTextField();
        jTFProvince = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTFTel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaShow = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame.setVisible(true);
        jInternalFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPCert.setBackground(new java.awt.Color(204, 204, 204));
        jPCert.setBorder(javax.swing.BorderFactory.createTitledBorder("证书"));
        jPCert.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPCertStorage.setBorder(javax.swing.BorderFactory.createTitledBorder("证书存储"));

        PathShow.setBackground(new java.awt.Color(255, 255, 255));
        PathShow.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        btnFileChoose.setBackground(new java.awt.Color(255, 255, 204));
        btnFileChoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ouc/minica/img/文件按钮.png"))); // NOI18N
        btnFileChoose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFileChooseMouseClicked(evt);
            }
        });

        jLabelFile.setText("磁盘文件：");

        javax.swing.GroupLayout jPCertStorageLayout = new javax.swing.GroupLayout(jPCertStorage);
        jPCertStorage.setLayout(jPCertStorageLayout);
        jPCertStorageLayout.setHorizontalGroup(
            jPCertStorageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCertStorageLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelFile, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PathShow, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnFileChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPCertStorageLayout.setVerticalGroup(
            jPCertStorageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCertStorageLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPCertStorageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCertStorageLayout.createSequentialGroup()
                        .addGroup(jPCertStorageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PathShow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFileChoose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabelFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPCert.add(jPCertStorage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 470, -1));

        btnMake.setText("数证制作");
        btnMake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMakeMouseClicked(evt);
            }
        });
        jPCert.add(btnMake, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        jInternalFrame.getContentPane().add(jPCert, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 302, 493, 150));

        jPConstraint.setBackground(new java.awt.Color(204, 204, 204));
        jPConstraint.setBorder(javax.swing.BorderFactory.createTitledBorder("基本约束"));
        jPConstraint.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jPConstraint.setLayout(null);

        jPCertForm.setBorder(javax.swing.BorderFactory.createTitledBorder("证书格式"));
        jPCertForm.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N

        jLabelDER.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabelDER.setText(" DER格式");

        javax.swing.GroupLayout jPCertFormLayout = new javax.swing.GroupLayout(jPCertForm);
        jPCertForm.setLayout(jPCertFormLayout);
        jPCertFormLayout.setHorizontalGroup(
            jPCertFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCertFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDER)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPCertFormLayout.setVerticalGroup(
            jPCertFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCertFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDER, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPConstraint.add(jPCertForm);
        jPCertForm.setBounds(7, 17, 112, 100);

        jPCertFunction.setBorder(javax.swing.BorderFactory.createTitledBorder("证书功能"));

        jLabelKeyLength.setText("密钥长度：");

        jLabelEffDate.setText("证书有效期：");

        jTextDAY.setText("365");

        jLabelDay.setText("天");

        jLabelLEN.setText("位");

        keyLength.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "512", "768", "1024", "1536", "2048", "3072", "4096", "5120", "6144", "7168", "8192", "9216", "10240", "" }));

        javax.swing.GroupLayout jPCertFunctionLayout = new javax.swing.GroupLayout(jPCertFunction);
        jPCertFunction.setLayout(jPCertFunctionLayout);
        jPCertFunctionLayout.setHorizontalGroup(
            jPCertFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCertFunctionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCertFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCertFunctionLayout.createSequentialGroup()
                        .addComponent(jLabelEffDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextDAY, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(jPCertFunctionLayout.createSequentialGroup()
                        .addComponent(jLabelKeyLength)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(keyLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLEN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPCertFunctionLayout.setVerticalGroup(
            jPCertFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCertFunctionLayout.createSequentialGroup()
                .addGroup(jPCertFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEffDate)
                    .addComponent(jTextDAY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPCertFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKeyLength)
                    .addComponent(keyLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLEN))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPConstraint.add(jPCertFunction);
        jPCertFunction.setBounds(130, 20, 190, 100);

        jPCertStyle.setBorder(javax.swing.BorderFactory.createTitledBorder("证书类型"));
        jPCertStyle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(jRBROOT);
        jRBROOT.setText("根证书");
        jPCertStyle.add(jRBROOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        buttonGroup1.add(jRBnDIY);
        jRBnDIY.setSelected(true);
        jRBnDIY.setText("自定义式");
        jPCertStyle.add(jRBnDIY, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 20));

        jPConstraint.add(jPCertStyle);
        jPCertStyle.setBounds(340, 20, 140, 100);

        jInternalFrame.getContentPane().add(jPConstraint, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 165, 490, 130));

        jLabelNavImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ouc/minica/img/导航3.jpg"))); // NOI18N
        jInternalFrame.getContentPane().add(jLabelNavImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 493, 28));

        jPInfo.setBackground(new java.awt.Color(204, 204, 204));
        jPInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("基本信息"));
        jPInfo.setLayout(new javax.swing.BoxLayout(jPInfo, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelContent.setText("内容");
        jLabelContent.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel1.add(jLabelContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 300, 20));

        jCBCountry.setSelected(true);
        jPanel1.add(jCBCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        jCBProvince.setSelected(true);
        jPanel1.add(jCBProvince, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        jCBCity.setSelected(true);
        jPanel1.add(jCBCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        jCBCommunity.setSelected(true);
        jPanel1.add(jCBCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jCBUnit.setSelected(true);
        jPanel1.add(jCBUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        jCBMail.setSelected(true);
        jPanel1.add(jCBMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        jCBSurName.setSelected(true);
        jPanel1.add(jCBSurName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        jCBTeleNum.setSelected(true);
        jPanel1.add(jCBTeleNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        jCBStreet.setSelected(true);
        jPanel1.add(jCBStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        jCBPoBox.setSelected(true);
        jPanel1.add(jCBPoBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        jCBPoCode.setSelected(true);
        jPanel1.add(jCBPoCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));

        jCBID.setSelected(true);
        jPanel1.add(jCBID, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        jCBName.setSelected(true);
        jPanel1.add(jCBName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jLabelImage1.setFont(new java.awt.Font("宋体", 0, 8)); // NOI18N
        jLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ouc/minica/img/复选框.png"))); // NOI18N
        jPanel1.add(jLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        jLabelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ouc/minica/img/复选框.png"))); // NOI18N
        jPanel1.add(jLabelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 30, 20));

        jLabelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ouc/minica/img/复选框.png"))); // NOI18N
        jPanel1.add(jLabelImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 30, 20));

        jLabelImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ouc/minica/img/复选框.png"))); // NOI18N
        jPanel1.add(jLabelImage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 30, 20));

        jLabelImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ouc/minica/img/复选框.png"))); // NOI18N
        jLabelImage5.setText("jLabel30");
        jPanel1.add(jLabelImage5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 30, 20));

        jLabelImage6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ouc/minica/img/复选框.png"))); // NOI18N
        jLabelImage6.setText("jLabel31");
        jPanel1.add(jLabelImage6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 30, 20));

        jLabelImage7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ouc/minica/img/复选框.png"))); // NOI18N
        jLabelImage7.setText("jLabel32");
        jPanel1.add(jLabelImage7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 30, 20));

        jLabelImage8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ouc/minica/img/复选框.png"))); // NOI18N
        jLabelImage8.setText("jLabel33");
        jPanel1.add(jLabelImage8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 30, 20));

        jLabelImage9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ouc/minica/img/复选框.png"))); // NOI18N
        jLabelImage9.setText("jLabel34");
        jPanel1.add(jLabelImage9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 30, 20));

        jLabelImage10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ouc/minica/img/复选框.png"))); // NOI18N
        jLabelImage10.setText("jLabel35");
        jPanel1.add(jLabelImage10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 30, 20));

        jLabelImage11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ouc/minica/img/复选框.png"))); // NOI18N
        jLabelImage11.setText("jLabel36");
        jPanel1.add(jLabelImage11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 30, 20));

        jLabelImage12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ouc/minica/img/复选框.png"))); // NOI18N
        jLabelImage12.setText("jLabel37");
        jPanel1.add(jLabelImage12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 30, 20));

        jLabelImage13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ouc/minica/img/复选框.png"))); // NOI18N
        jLabelImage13.setText("jLabel38");
        jPanel1.add(jLabelImage13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 30, 20));

        jCBPhoneNum.setSelected(true);
        jPanel1.add(jCBPhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        jLabelImage14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ouc/minica/img/复选框.png"))); // NOI18N
        jPanel1.add(jLabelImage14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 30, 20));

        jLabelTextName.setText(" 字段名称");
        jLabelTextName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel1.add(jLabelTextName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 20));
        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -10, -1, -1));

        jTFname.setBackground(new java.awt.Color(204, 204, 204));
        jTFname.setText("MiniCA");
        jPanel1.add(jTFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 300, -1));

        jTFcountry.setText("China");
        jPanel1.add(jTFcountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 300, -1));

        jTFprovince.setBackground(new java.awt.Color(204, 204, 204));
        jTFprovince.setText("HeBei");
        jPanel1.add(jTFprovince, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 300, -1));

        jTFcity.setText("ShiJiaZhuang");
        jPanel1.add(jTFcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 300, -1));

        jTFcommunity.setBackground(new java.awt.Color(204, 204, 204));
        jTFcommunity.setText("MiniSoft");
        jPanel1.add(jTFcommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 300, -1));

        jTFunit.setText("MiniCA");
        jPanel1.add(jTFunit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 300, -1));

        jTFemail.setBackground(new java.awt.Color(204, 204, 204));
        jTFemail.setText("hpxs@hotmail.com");
        jPanel1.add(jTFemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 300, -1));

        jTFsurname.setText("SN");
        jPanel1.add(jTFsurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 300, -1));

        jTFtelephone.setBackground(new java.awt.Color(204, 204, 204));
        jTFtelephone.setText("8888-8888888");
        jPanel1.add(jTFtelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 300, -1));

        jTFstreet.setText("88 jinguang avenue");
        jPanel1.add(jTFstreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 300, -1));

        jTFpobox.setBackground(new java.awt.Color(204, 204, 204));
        jTFpobox.setText("888888");
        jPanel1.add(jTFpobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 300, -1));

        jTFpocode.setText("888888");
        jPanel1.add(jTFpocode, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 300, -1));

        jTFID.setBackground(new java.awt.Color(204, 204, 204));
        jTFID.setText("4114811995********");
        jPanel1.add(jTFID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 300, -1));

        jTFphone.setText("132108*****");
        jPanel1.add(jTFphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 300, -1));

        jTFName.setEditable(false);
        jTFName.setBackground(new java.awt.Color(204, 204, 204));
        jTFName.setText("名称");
        jPanel1.add(jTFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 130, -1));

        jTFCountry.setEditable(false);
        jTFCountry.setText("国家");
        jPanel1.add(jTFCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 130, -1));

        jTFProvince.setEditable(false);
        jTFProvince.setBackground(new java.awt.Color(204, 204, 204));
        jTFProvince.setText("省份");
        jPanel1.add(jTFProvince, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 130, -1));

        jTextField2.setEditable(false);
        jTextField2.setText("城市");
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 130, -1));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(204, 204, 204));
        jTextField3.setText("组织");
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 130, -1));

        jTextField4.setEditable(false);
        jTextField4.setText("单位");
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 130, -1));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("电子邮件");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 130, -1));

        jTextField5.setEditable(false);
        jTextField5.setText("姓氏");
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 130, -1));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(204, 204, 204));
        jTextField6.setText("固定电话号码");
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 130, -1));

        jTextField7.setEditable(false);
        jTextField7.setText("街道");
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 130, -1));

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(204, 204, 204));
        jTextField8.setText("邮政信箱");
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 130, -1));

        jTextField9.setEditable(false);
        jTextField9.setText("邮政编码");
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 130, -1));

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(204, 204, 204));
        jTextField10.setText("身份证号码");
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 130, -1));

        jTFTel.setEditable(false);
        jTFTel.setText("电话号码");
        jPanel1.add(jTFTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 130, -1));

        jScrollPane4.setViewportView(jPanel1);

        jPInfo.add(jScrollPane4);

        jInternalFrame.getContentPane().add(jPInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 34, 493, 125));

        jTextAreaShow.setColumns(20);
        jTextAreaShow.setRows(5);
        jScrollPane1.setViewportView(jTextAreaShow);

        jInternalFrame.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 490, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );

        try {
            jInternalFrame.setIcon(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFileChooseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFileChooseMouseClicked
             JFileChooser filechooser= new JFileChooser();
             filechooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
             filechooser.setDialogTitle("Select path to save");
             int result = filechooser.showOpenDialog(this);
             if (result == JFileChooser.APPROVE_OPTION) {
                path = filechooser.getSelectedFile().getAbsolutePath();
                PathShow.setText(path);
             }        
    }//GEN-LAST:event_btnFileChooseMouseClicked

    private void getStringInfo(String[] string)
     {
        jTextAreaShow.setText("加载内部证书...");
        if(jCBName.isSelected())
        {
            string[0]=jTFname.getText();
            subjectDN=subjectDN+"CN="+string[0]+"，，";
        }
        if(jCBCountry.isSelected())
        {
            string[1]="C = "+jTFcountry.getText();
            subjectDN=subjectDN+string[1]+"，";
        }
        if(jCBProvince.isSelected())
        {
            string[2]="ST = "+jTFprovince.getText();
            subjectDN=subjectDN+string[2]+"，";
        }
        if(jCBCity.isSelected())
        {
            string[3]="L = "+jTFcity.getText();
            subjectDN=subjectDN+string[3]+"，";
        } 
         if(jCBCommunity.isSelected())
        {
            string[4]="O = "+jTFcommunity.getText();
            subjectDN=subjectDN+string[4]+"，";
        }
          if(jCBUnit.isSelected())
        {
            string[5]="OU = "+jTFunit.getText();
            subjectDN=subjectDN+string[5]+"，";
        }
           if(jCBMail.isSelected())
        {
            string[6]="EmailAddress = "+ jTFemail.getText();
            subjectDN=subjectDN+string[6]+"，";
        }
            if(jCBSurName.isSelected())
        {
            string[7]="SN = "+jTFsurname.getText();
            subjectDN=subjectDN+string[7]+"，";
        }
            if(jCBTeleNum.isSelected())
        {
            string[8]="TELEPHONE_NUMBER = "+jTFtelephone.getText();
            subjectDN=subjectDN+string[8]+"，";
             
        }
            
            if(jCBStreet.isSelected())
        {
            string[9]="STREET = "+jTFstreet.getText();
            //subjectDN=subjectDN+string[9]+",";
            subjectDN=subjectDN+string[9]+"，";
            
        }
            if(jCBPoBox.isSelected())
        {
            string[10]="POBox = "+jTFpobox.getText();
            //subjectDN=subjectDN+string[10]+",";
            subjectDN=subjectDN+string[10]+"，";
           
        } 
            if(jCBPoCode.isSelected())
        {
            string[11]="PostalCode = "+jTFpocode.getText();
            //subjectDN=subjectDN+string[11]+",";
            subjectDN=subjectDN+string[11]+"，";
            
        } 
            if(jCBID.isSelected())
        {
            string[12]="UNIQUE_IDENTIFIER = "+jTFID.getText();
            //subjectDN=subjectDN+string[12]+",";
            subjectDN=subjectDN+string[12]+"，";
            
        } 
            if(jCBPhoneNum.isSelected())
        {
            string[13]="T = "+jTFphone.getText();
            //subjectDN=subjectDN+string[13]+",";
            subjectDN=subjectDN+string[13]+"，";
            
        }
    }
   
   public static Date addDate(Date d,long day)//获得证书的有效日期
   {
         long time = d.getTime(); 
         day = day*24*60*60*1000; 
         time+=day; 
         return new Date(time);
  }
   public int getDay()//获得有效天数
   {
       int a;
       String text;
       text=jTextDAY.getText();
       a= Integer.valueOf(text);
       return a;
    }
    public KeyPair generateKeyPair(int seed) throws NoSuchAlgorithmException {
        KeyPairGenerator kpg = KeyPairGenerator.getInstance("RSA");//返回用"RSA"加密算法创建的KeyPairGenerator（生成密钥对）单类实例，没有重新创建，存在调出原有实例
        length=Integer.parseInt(keyLength.getSelectedItem().toString());//得到密钥长度Integer.parseInt(month1.getselecteditem())
        kpg.initialize(length, new SecureRandom(new byte[seed]));//长为seed长度的字节，并用此生成强随机数序列，用于初始化密钥对生成器
        KeyPair keyPair = kpg.generateKeyPair();//keyPair保存生成的密钥对
        return keyPair;
    }
    //设置加密提供者
    static {
        Security.addProvider(new BouncyCastleProvider());//函数参数是加密提供者，里面包含了各种加密方法，生成证书格式等
    }
    public X509Certificate generateCert(KeyPair keyPair_root,KeyPair keyPair_user) throws InvalidKeyException, NoSuchProviderException, SecurityException, SignatureException, UnsupportedEncodingException {
        X509V3CertificateGenerator certGen = new X509V3CertificateGenerator();//实例化实现证书生成对象
        X509Certificate cert = null;//证书设置为空
        certGen.setSerialNumber(new BigInteger(serialnum));//利用传递的序列号设置证书的序列号
        if(jRBROOT.isSelected()){
            certGen.setIssuerDN(new X509Name(subjectDN));
            //certGen.setIssuerDN(new X509Name(buffer.toString()));
        } else {
            certGen.setIssuerDN(new X509Name("CN=Miss, OU=Network Security, O=OUC, C=China"));//设置证书颁发者的名字
        }
        Date curday=new Date();
        long num=getDay();
        Date effday=addDate(curday,num);
        certGen.setNotBefore(curday);//设置有效日期起止时间,当前系统的时间为起止日期
        certGen.setNotAfter(effday);//设置有效日期结束时间
        subjectDN =subjectDN.substring(0,subjectDN.length()-1);
        //System.out.print(subjectDN);
        String newStr = new String(subjectDN.getBytes(), "UTF-8");
        certGen.setSubjectDN(new X509Name(newStr));//设置指定人的信息
        //certGen.setSubjectDN(new X509Name(buffer.toString()));//设置指定人的信息
        certGen.setPublicKey(keyPair_user.getPublic());//使用者获得密钥对里的公钥并传给证书生成公钥信息
        certGen.setSignatureAlgorithm("SHA1WithRSA");//指定该证书的签名算法
        cert = certGen.generateX509Certificate(keyPair_root.getPrivate(), "BC");//用私钥产生签名
        return cert;
    }

    private void btnMakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMakeMouseClicked
       
              getStringInfo(info);
              KeyPair keyPair_root = null;
              KeyPair keyPair_user = null;
              X509Certificate cert=null;
              try {
                  keyPair_root = generateKeyPair(10); //10作为种子传递
              } catch (NoSuchAlgorithmException ex) {
                  Logger.getLogger(GenerateFrame.class.getName()).log(Level.SEVERE, null, ex);
              }
              //根证书
              if(jRBROOT.isSelected()){
                   try {
                      cert = generateCert(keyPair_root,keyPair_root);
                      jTextAreaShow.setText("加载内部证书...\n" + "生成证书成功");
                  } catch (InvalidKeyException | NoSuchProviderException | SecurityException | SignatureException ex) {
                      Logger.getLogger(GenerateFrame.class.getName()).log(Level.SEVERE, null, ex);
                  } catch (UnsupportedEncodingException ex) {
                      Logger.getLogger(GenerateFrame.class.getName()).log(Level.SEVERE, null, ex);
                  }
              }
              //签发证书
              else{
                  try {
                      keyPair_user = generateKeyPair(100);
                  } catch (NoSuchAlgorithmException ex) {
                      Logger.getLogger(GenerateFrame.class.getName()).log(Level.SEVERE, null, ex);
                  }
                  try {
                      cert = generateCert(keyPair_root,keyPair_user);
                      jTextAreaShow.setText("加载内部证书...\n" + "生成证书成功");
                  } catch (InvalidKeyException | NoSuchProviderException | SecurityException | SignatureException ex) {
                      Logger.getLogger(GenerateFrame.class.getName()).log(Level.SEVERE, null, ex);
                  } catch (UnsupportedEncodingException ex) {
                      Logger.getLogger(GenerateFrame.class.getName()).log(Level.SEVERE, null, ex);
                  }
              }
              FileOutputStream fos = null;
               String certPath = path+info[0]+".cer"; 
              String last = path.substring(path.length()-1,path.length());
              String a = "/";
              boolean flag = last.equals(path);
              if(!flag) certPath = path+"/"+info[0]+".cer"; 
             try {
                   fos = new FileOutputStream(certPath);
             } catch (FileNotFoundException ex) {
                   Logger.getLogger(GenerateFrame.class.getName()).log(Level.SEVERE, null, ex);
             }
             try {
                   fos.write(cert.getEncoded());//DER编码
             } catch (CertificateEncodingException | IOException ex) {
                    Logger.getLogger(GenerateFrame.class.getName()).log(Level.SEVERE, null, ex);
             }
             try {
                    fos.close();
             } catch (IOException ex) {
                 ex.printStackTrace();
                  Logger.getLogger(GenerateFrame.class.getName()).log(Level.SEVERE, null, ex);
                  
               }
              
        
    }//GEN-LAST:event_btnMakeMouseClicked
    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerateFrame().setVisible(true);
               
            }
        });
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PathShow;
    private javax.swing.JButton btnFileChoose;
    private javax.swing.JButton btnMake;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCBCity;
    private javax.swing.JCheckBox jCBCommunity;
    private javax.swing.JCheckBox jCBCountry;
    private javax.swing.JCheckBox jCBID;
    private javax.swing.JCheckBox jCBMail;
    private javax.swing.JCheckBox jCBName;
    private javax.swing.JCheckBox jCBPhoneNum;
    private javax.swing.JCheckBox jCBPoBox;
    private javax.swing.JCheckBox jCBPoCode;
    private javax.swing.JCheckBox jCBProvince;
    private javax.swing.JCheckBox jCBStreet;
    private javax.swing.JCheckBox jCBSurName;
    private javax.swing.JCheckBox jCBTeleNum;
    private javax.swing.JCheckBox jCBUnit;
    private javax.swing.JInternalFrame jInternalFrame;
    private javax.swing.JLabel jLabelContent;
    private javax.swing.JLabel jLabelDER;
    private javax.swing.JLabel jLabelDay;
    private javax.swing.JLabel jLabelEffDate;
    private javax.swing.JLabel jLabelFile;
    private javax.swing.JLabel jLabelImage1;
    private javax.swing.JLabel jLabelImage10;
    private javax.swing.JLabel jLabelImage11;
    private javax.swing.JLabel jLabelImage12;
    private javax.swing.JLabel jLabelImage13;
    private javax.swing.JLabel jLabelImage14;
    private javax.swing.JLabel jLabelImage2;
    private javax.swing.JLabel jLabelImage3;
    private javax.swing.JLabel jLabelImage4;
    private javax.swing.JLabel jLabelImage5;
    private javax.swing.JLabel jLabelImage6;
    private javax.swing.JLabel jLabelImage7;
    private javax.swing.JLabel jLabelImage8;
    private javax.swing.JLabel jLabelImage9;
    private javax.swing.JLabel jLabelKeyLength;
    private javax.swing.JLabel jLabelLEN;
    private javax.swing.JLabel jLabelNavImage;
    private javax.swing.JLabel jLabelTextName;
    private javax.swing.JPanel jPCert;
    private javax.swing.JPanel jPCertForm;
    private javax.swing.JPanel jPCertFunction;
    private javax.swing.JPanel jPCertStorage;
    private javax.swing.JPanel jPCertStyle;
    private javax.swing.JPanel jPConstraint;
    private javax.swing.JPanel jPInfo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBROOT;
    private javax.swing.JRadioButton jRBnDIY;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTFCountry;
    private javax.swing.JTextField jTFID;
    private javax.swing.JTextField jTFName;
    private javax.swing.JTextField jTFProvince;
    private javax.swing.JTextField jTFTel;
    private javax.swing.JTextField jTFcity;
    private javax.swing.JTextField jTFcommunity;
    private javax.swing.JTextField jTFcountry;
    private javax.swing.JTextField jTFemail;
    private javax.swing.JTextField jTFname;
    private javax.swing.JTextField jTFphone;
    private javax.swing.JTextField jTFpobox;
    private javax.swing.JTextField jTFpocode;
    private javax.swing.JTextField jTFprovince;
    private javax.swing.JTextField jTFstreet;
    private javax.swing.JTextField jTFsurname;
    private javax.swing.JTextField jTFtelephone;
    private javax.swing.JTextField jTFunit;
    private javax.swing.JTextArea jTextAreaShow;
    private javax.swing.JTextField jTextDAY;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JComboBox keyLength;
    // End of variables declaration//GEN-END:variables
}
